version: "3.1"
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pedbot
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=admin --execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 10s
      retries: 10
  react:
    build: ./library-front-end
    container_name: react
    restart: always
    ports:
      - 5173:5173
    volumes:
      - ./library-front-end:/usr/react
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  app:
    build: ./nestjs-library
    container_name: app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
    volumes:
      - ./nestjs-library:/usr/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
volumes:
  mysql_data: